import React from 'react';
import {Text, View, StyleSheet, ScrollView, SafeAreaView} from 'react-native';

const PrivacyPolicy = () => {
	return (
		<SafeAreaView style={{flex: 1, backgroundColor: '#fff', padding: 5}}>
			<ScrollView>
				<Text style={styles.heading}>Privacy-Policy-Pinch</Text>
				<Text style={styles.text}>
					Last updated: 23th September 2022
				</Text>
				<Text style={styles.text}>
					PLEASE READ THIS POLICY CAREFULLY BEFORE USING THE PINCH
					PLATFORM
				</Text>
				<Text style={styles.text}>
					The Pinch Platform (“Platform”) is made available by Stint
					Infotech Pvt. Ltd. (“our”, “us”, “we”, “Company”). In order
					to provide you with access to our Platform, we need to
					collect various data and information from you. This Privacy
					Policy (“Policy”) details how this data and information is
					collected, retained, shared, stored, and processed by us. We
					may revise this Policy as well as update the Platform from
					time to time. Please visit this page regularly to take
					notice of any changes we make. Continued use of the Platform
					after an update constitutes consent to the updated policy.
					If you do not agree with any part of this Policy, please
					stop using our Platform immediately. This Policy is
					incorporated within and is to be read with our Terms of Use.
					Words and phrases not defined in this Policy shall have the
					same meaning as provided in the Terms of Use.
				</Text>
				<Text style={styles.heading}>Information we collect</Text>
				<Text style={styles.text}>
					We collect the data you provide only to ensure that we can
					provide you access to our Platform in the best manner
					possible. By using the Platform, you consent to provide us
					data in the ways listed below.
				</Text>
				<Text style={styles.text}>
					Data you input: We collect the information that you actively
					input into the Platform:
				</Text>
				<Text style={styles.text}>
					Pinch Account data: We collect the data you provide to us
					when you create or update your Pinch Account. This includes
					your name, phone number, email id, Binance account details,
					Bitbns account details and any information provided therein
					by you (including details of all executed orders on Bitbns
					and Binance, all open orders on Bitbns and Binance, deposits
					and withdrawal history, user ID assigned by Bitbns and
					Binance, and email address used for creating a Bitbns
					account and Binance account). We may require you to share
					further data at a later date to confirm the veracity of your
					information or pursuant to any additional features added to
					the Platform.
				</Text>

				<Text style={styles.text}>
					Feedback and other data: We collect and record: (i) any
					emails you write to us; (ii) the calls you make to our call
					centres and/or customer service personnel; and (iii)
					feedback or comments you provide to us on the Platform,
					including any crash reports and log reports generated by
					you.
				</Text>

				<Text style={styles.text}>
					Data collected from your use. We collect the following data
					generated owing to and pursuant to your use of the Platform:
				</Text>
				<Text style={styles.text}>
					Platform usage data: We collect data on your interaction
					with our Platform, i.e., Platform access dates and times,
					features or pages viewed, crashes and other system activity
					like the comment, like, shares and type of browser used to
					access the Platform, and third-party sites or services used
					before or in the course of interacting with our Platform.
				</Text>

				<Text style={styles.text}>
					Platform usage data: We collect data on your interaction
					with our Platform, i.e., Platform access dates and times,
					features or pages viewed, crashes and other system activity
					like the comment, like, shares and type of browser used to
					access the Platform, and third-party sites or services used
					before or in the course of interacting with our Platform.
				</Text>

				<Text style={styles.text}>
					Device data: We may collect data about the devices used to
					access our Platform, including the hardware models, device
					IP address, operating systems and versions, software,
					preferred languages, unique device identifiers, serial
					numbers, browser type, mobile app, file names and types,
					plugins.
				</Text>

				<Text style={styles.text}>
					SMS data: We may access your SMS data to verify the one-time
					password (OTP) sent to your mobile device.
				</Text>

				<Text style={styles.text}>
					Cookies, log files, web beacons and tracking pixels: We also
					collect information through the use of “cookies”, “log
					files”, “web beacons” and “tracking pixels”, and similar
					technologies to understand how you navigate through the
					Platform to learn your preferences. Cookies are small text
					files that web servers place on your device; they are
					designed to store basic information and to help websites and
					apps recognise your browser. We may use both session cookies
					and persistent cookies. A session cookie disappears after
					you close your browser. A persistent cookie remains after
					you close your browser and may be accessed every time you
					use the Platform. Log files track actions that occur on our
					Platform, and collect data including your IP address,
					browser type, internet service provider, referring and exit
					pages, and date and time stamps. Web beacons, tags and
					pixels are electronic files used to record information about
					how you browse the Platform.
				</Text>

				<Text style={styles.text}>
					Information received from third parties. We may also be
					working closely with third parties (including, for example,
					business partners, technical sub-contractors, and analytics
					providers) and may receive information about you from such
					sources. Such data may be shared internally and combined
					with data collected under Section 1.2 (Data collected from
					your use) above.
				</Text>
				<Text style={styles.heading}>Use of Collected Data</Text>
				<Text style={styles.text}>
					The data we collect from you will be used for the following
					purposes:
					{'\n'}
					{'\n'}
					For enabling the Platform. We use the data collected to
					enable, personalise, maintain and improve our Platform. This
					includes using the data to:{'\n'}
					{'\n'}Authenticate your Pinch Account and connect it to your
					Bitbns and Binance account; {'\n'}
					{'\n'}Conduct data analysis, testing, and research; and
					monitor and analyse usage and activity trends;{'\n'}
					{'\n'}
					Create and update your Pinch Account; {'\n'}
					{'\n'}Perform internal operations necessary to provide you
					and improve our Platform, including troubleshooting software
					bugs and operational problems; {'\n'}
					{'\n'}and Suggest your preview screens created by you and
					show it to the users you choose to share with {'\n'}
					{'\n'}Serve relevant content to you, including content
					served by third parties.{'\n'}
					{'\n'}For enabling customer support and communication. We
					use the information to provide customer support and train
					our customer service executives. We may further add features
					that allow you to call us (through the Platform or
					otherwise), similarly, we may also need to contact you
					through the Platform.{'\n'}
					{'\n'}For marketing and outreach. We use the data we collect
					to market our Platform. This includes sharing your feedback,
					ratings and screen names for purely promotional and
					marketing purposes. Such promotion and marketing may be done
					via hoardings, banners, pamphlets etc. {'\n'}
					{'\n'}For fraud detection and preventing misuse. We use the
					data we collect to detect fraudulent usage of the Platform
					and/or misuse of any of the features of the Platform. {'\n'}
					{'\n'}For legal compliance and requirements. We use the data
					we collect to address claims or disputes relating to the use
					of our Platform, as otherwise allowed by applicable law, or
					as requested by regulators, government entities, and
					official inquiries.
				</Text>

				<Text style={styles.heading}>Sharing of Data</Text>
				<Text style={styles.text}>
					We do not share any personal data about you with any third
					parties unless necessary. We may enter into agreements or
					arrangements to enable the use of our Platform. Our
					agreements with third parties impose an obligation on these
					third parties to handle your personal data with the same
					level of protection as outlined in this Privacy Policy. We
					have detailed the manner in which we share the collected
					data below:
				</Text>
				<Text style={styles.text}>Service Providers.</Text>
				<Text style={styles.text}>Change in Control.</Text>
				<Text style={styles.text}>Law Enforcement.</Text>
				<Text style={styles.text}>
					satisfy any applicable law, regulation, legal process, or
					governmental request;
				</Text>
				<Text style={styles.text}>
					enforce applicable terms of use, including investigation of
					potential violations thereof;
				</Text>
				<Text style={styles.text}>
					detect, prevent, or otherwise address illegal or suspected
					illegal activities (including payment fraud), security or
					technical issues; and/or
				</Text>
				<Text style={styles.text}>
					protect against harm to our rights, property or safety, our
					users or the public, as required or permitted by law.
				</Text>

				<Text style={styles.heading}>Consent</Text>
				<Text style={styles.text}>
					By setting up a Pinch Account, you agree to our processing,
					storage, usage, and sharing of data provided by you pursuant
					to this Policy. If you do not agree with any of the terms of
					this Policy or the Terms of Use or wish to revoke any
					consent you have provided to us, please write to our
					grievance officer, details of whom are provided below.
					However, if you revoke any mandatory permissions then we may
					have to cease providing you with access to the Platform and
					services therein.
				</Text>

				<Text style={styles.heading}>Your Rights</Text>
				<Text style={styles.text}>
					It is important to us that you remain in control of your
					data. Please write to us if you wish to exercise any of your
					rights provided below:
				</Text>
				<Text style={styles.text}>Right to rectification.</Text>
				<Text style={styles.text}>Right to erasure.</Text>
				<Text style={styles.text}>
					Right to confirmation and access.
				</Text>
				<Text style={styles.text}>Right to withdraw consent.</Text>

				<Text style={styles.text}>Right to opt-out.</Text>
				<Text style={styles.heading}>Data Retention</Text>
				<Text style={styles.text}>
					We shall retain the information you provide to facilitate
					your smooth and uninterrupted use of the Platform, and to:
				</Text>
				<Text style={styles.text}>Cross Border Data Transfer</Text>
				<Text style={styles.text}>
					Your personal data held by us may be transferred to other
					countries outside your residential country for any of the
					purposes described in this Policy, subject to applicable
					law. You understand and accept that these countries may have
					differing (and potentially less stringent) laws relating to
					the degree of confidentiality afforded to the information it
					holds and that such information can become subject to the
					laws and disclosure requirements of such countries,
					including disclosure to governmental bodies, regulatory
					agencies and private persons, as a result of applicable
					governmental or regulatory inquiry, court order or other
					similar processes. In addition, a number of countries have
					agreements with other countries providing for exchange of
					information for law enforcement, tax and other purposes.If
					we transfer your personal data to third parties for purposes
					stated in this Policy, we will use our best endeavours to
					put in place appropriate controls and safeguards to ensure
					that your personal data is kept accurate, adequately
					protected, and processed only for specified and reasonable
					purposes in a manner that is fair, transparent and has a
					lawful basis, and is stored for no longer than is absolutely
					necessary.
				</Text>
				<Text style={styles.heading}>Data Security</Text>
				<Text style={styles.text}>
					We use appropriate technical and organisational security
					measures to ensure the protection of personal data. The
					transfer of personal data between your end device and us is
					generally carried out in an encrypted form. You can identify
					an encrypted connection for example by the lock symbol in
					the address line of your browser. If you communicate with us
					by e-mail, access by third parties cannot be ruled out.
					However, remember that no method of transmission over the
					internet, or method of electronic storage is entirely secure
					and reliable, and we cannot guarantee its absolute security.
				</Text>

				<Text style={styles.heading}>Communications From Us</Text>
				<Text style={styles.text}>
					We may from time to time send you Platform-related
					announcements when we consider them necessary and in your
					interest. You may continue to receive such communication
					from us even after you have opted out of receiving emails
					from us.
				</Text>
				<Text style={styles.heading}>Grievances and Redressal</Text>
				<Text style={styles.text}>
					We are committed to promptly address any grievances that you
					might have in connection with our use of any information
					that you provide to us. Accordingly, you may communicate any
					grievance that you might have by emailing Shubham Sharma
					(feedback@pinch-me.com). Please note that if you contact us
					to assist you, for your safety and ours, we may need to
					authenticate your identity before fulfilling your request.
				</Text>

				<Text style={styles.heading}>Children's Privacy</Text>
				<Text style={styles.text}>
					Our website is directed to be used by adults (persons
					eighteen years of age or above) only. If you are not an
					adult, while you may look at our site, you should not
					register or submit personal data to us. We or our associates
					/affiliates do not knowingly collect information from
					minors.
				</Text>
			</ScrollView>
		</SafeAreaView>
	);
};
const styles = StyleSheet.create({
	heading: {
		fontSize: 20,
		fontFamily: 'Montserrat-Bold',
		color: '#000',
		margin: 8,
		lineHeight: 24
	},
	text: {
		fontSize: 16,
		margin: 8,
		color: '#1F1F1F',
		fontFamily: 'Montserrat-Regular',
		lineHeight: 20
	}
});
export default PrivacyPolicy;
